INSERT INTO taxonname ("spid","name","fullname","rankid","treedefid","parentfullname") VALUES 
 (6237,"polonicum","Bembidion andreae polonicum",230,2,"Bembidion andreae")
,(6242,"illigeri","Bembidion genei illigeri",230,2,"Bembidion genei")
,(6280,"australis","Patrobus septentrionis australis",230,2,"Patrobus septentrionis")
,(6392,"silvicola","Amara quenseli silvicola",230,2,"Amara quenseli")
,(6718,"fuscipennis","Enochrus quadripunctatus fuscipennis",230,2,"Enochrus quadripunctatus")
,(6750,"brevipalpis","Helophorus guttulus brevipalpis",230,2,"Helophorus guttulus")
,(6796,"frontalis","Zeugophora scutellaris frontalis",230,2,"Zeugophora scutellaris")
,(6906,"var","Melolontha melolontha var",230,2,"Melolontha melolontha")
,(7028,"albofasciatus","Anaglyptus mysticus albofasciatus",230,2,"Anaglyptus mysticus")
,(7413,"latipalpes","Anaspis thoracica latipalpes",230,2,"Anaspis thoracica")
,(7620,"africaus","Lyctus bruueus africaus",230,2,"Lyctus bruueus")
,(8277,"nigrescens","Bombus sylvarum nigrescens",230,2,"Bombus sylvarum")
,(8288,"pallidofacies ","Bombus pascuorum pallidofacies ",230,2,"Bombus pascuorum")
,(8297,"soroeensis","Bombus soroeensis soroeensis",230,2,"Bombus soroeensis")
,(8298,"proteus","Bombus soroeensis proteus",230,2,"Bombus soroeensis")
,(8381,"cornigera","Osmia bicornis cornigera",230,2,"Osmia bicornis")
;