  -- To be run on Specify database
  --    Add to top:
  --       INSERT INTO taxonname ("spid","name","author","fullname","rankid","taxonRank", "treedefid","parentfullname", "taxonnumber", "taxonnrsource") VALUES 
  SELECT
	 -- CONCAT('(', t.TaxonID, ',"', t.Name, '","', COALESCE(t.author,'') , '","', TRIM(CONCAT(t.FullName, ' ', COALESCE(t.author,''))), '",', t.RankID ,',"', ttd.Name ,'", ', t.TaxonTreeDefID, ',"', p1.FullName, '","', COALESCE(t.text1,''), '","', COALESCE(t.text2,''), '"),' ) 
	 --   sqlstatement
	  t.TaxonID, t.FullName, t.author, t.RankID rankid, ttd.Name rankname, p1.FullName parentname, t.text1 taxonnr, t.text2 taxonnrsource 
 FROM taxon t
	LEFT JOIN taxon p1 ON p1.TaxonID = t.ParentID
	LEFT JOIN taxon p2 ON p2.TaxonID = p1.ParentID
	LEFT JOIN taxon p3 ON p3.TaxonID = p2.ParentID
	LEFT JOIN taxon p4 ON p4.TaxonID = p3.ParentID
	LEFT JOIN taxontreedefitem ttd ON t.rankID = ttd.RankID AND t.TaxonTreeDefID = ttd.TaxonTreeDefID

	WHERE
		t.taxontreedefid = 13 -- 13 for NHMD Botany, 5 for NHMD Entomology, 2 for NHMA Entomology
-- The following lines filter on taxon rank and should be adjusted accordingly
		-- AND t.RankID > 230 -- VarForma 
		-- AND t.RankID = 230 -- Subspecies
		-- AND t.RankID = 220 -- Species
		-- AND t.RankID <= 190   -- Highertaxa (including Subgenus). t.RankID >= 180 for Species-BatchN.sql - t.RankID <= 190 for Highertaxa.sql
-- The following lines are needed to restrict the taxa pulled out for NHMHD Entomology 
 /* 
 		AND (t.FullName IN ('Animalia', 'Arthropoda', 'Hexapoda', 'Insecta', 'Lepidoptera', 'Coleoptera', 'Aderidae','Agyrtidae','Alexiidae','Anthicidae','Anthribidae','Apionidae','Attelabidae','Biphyllidae','Bolboceratidae','Bostrichidae','Bothrideridae','Buprestidae','Byrrhidae','Byturidae','Cantharidae','Carabidae','Cerambycidae','Cerylonidae','Chrysomelidae','Ciidae','Clambidae','Cleridae','Coccinellidae','Corylophidae','Cryptophagidae','Cucujidae','Curculionidae','Dascillidae','Dasytidae','Dermestidae','Derodontidae','Drilidae','Dryopidae','Dytiscidae','Elateridae','Elmidae','Endomychidae','Erotylidae','Eucinetidae','Eucnemidae','Georissidae','Geotrupidae','Gyrinidae','Haliplidae','Helophoridae','Heteroceridae','Histeridae','Hydraenidae','Hydrochidae','Hydrophilidae','Hygrobiidae','Kateretidae','Laemophloeidae','Lampyridae','Latridiidae','Leiodidae','Limnichidae','Lucanidae','Lycidae','Lymexylidae','Malachiidae','Megalopodidae','Melandryidae','Meloidae','Microsporidae','Monotomidae','Mordellidae','Mycetophagidae','Nanophyidae','Nemonychidae','Nitidulidae','Nosodendridae','Noteridae','Oedemeridae','Orsodacnidae','Phalacridae','Phloeostichidae','Phloiophilidae','Prostomidae','Psephenidae','Ptiliidae','Ptinidae','Pyrochroidae','Pythidae','Rhynchitidae','Ripiphoridae','Salpingidae','Scarabaeidae','Scirtidae','Scraptiidae','Silphidae','Silvanidae','Spercheidae','Sphaeritidae','Sphindidae','Staphylinidae','Tenebrionidae','Tetratomidae','Throscidae','Trogidae','Trogossitidae','Zopheridae','Adelidae','Alucitidae','Argyresthiidae','Autostichidae','Batrachedridae','Bedelliidae','Blastobasidae','Bombycidae','Brahmaeidae','Bucculatricidae','Castniidae','Chimabachidae','Choreutidae','Coleophoridae','Cosmopterigidae','Cossidae','Crambidae','Depressariidae','Douglasiidae','Drepanidae','Elachistidae','Endromidae','Epermeniidae','Erebidae','Eriocraniidae','Ethmiidae','Euteliidae','Gelechiidae','Geometridae','Glyphipterigidae','Gracillariidae','Heliozelidae','Hepialidae','Hesperiidae','Incurvariidae','Lasiocampidae','Limacodidae','Lycaenidae','Lyonetiidae','Lypusidae','Micropterigidae','Momphidae','Nepticulidae','Noctuidae','Nolidae','Notodontidae','Nymphalidae','Oecophoridae','Opostegidae','Papilionidae','Parametriotidae','Peleopodidae','Pieridae','Plutellidae','Praydidae','Prodoxidae','Psychidae','Pterophoridae','Pyralidae','Riodinidae','Roeslerstammiidae','Saturniidae','Schreckensteiniidae','Scythrididae','Sesiidae','Sphingidae','Stathmopodidae','Tineidae','Tischeriidae','Tortricidae','Urodidae','Yponomeutidae','Ypsolophidae','Zygaenidae')
 		OR p1.FullName IN ('Aderidae','Agyrtidae','Alexiidae','Anthicidae','Anthribidae','Apionidae','Attelabidae','Biphyllidae','Bolboceratidae','Bostrichidae','Bothrideridae','Buprestidae','Byrrhidae','Byturidae','Cantharidae','Carabidae','Cerambycidae','Cerylonidae','Chrysomelidae','Ciidae','Clambidae','Cleridae','Coccinellidae','Corylophidae','Cryptophagidae','Cucujidae','Curculionidae','Dascillidae','Dasytidae','Dermestidae','Derodontidae','Drilidae','Dryopidae','Dytiscidae','Elateridae','Elmidae','Endomychidae','Erotylidae','Eucinetidae','Eucnemidae','Georissidae','Geotrupidae','Gyrinidae','Haliplidae','Helophoridae','Heteroceridae','Histeridae','Hydraenidae','Hydrochidae','Hydrophilidae','Hygrobiidae','Kateretidae','Laemophloeidae','Lampyridae','Latridiidae','Leiodidae','Limnichidae','Lucanidae','Lycidae','Lymexylidae','Malachiidae','Megalopodidae','Melandryidae','Meloidae','Microsporidae','Monotomidae','Mordellidae','Mycetophagidae','Nanophyidae','Nemonychidae','Nitidulidae','Nosodendridae','Noteridae','Oedemeridae','Orsodacnidae','Phalacridae','Phloeostichidae','Phloiophilidae','Prostomidae','Psephenidae','Ptiliidae','Ptinidae','Pyrochroidae','Pythidae','Rhynchitidae','Ripiphoridae','Salpingidae','Scarabaeidae','Scirtidae','Scraptiidae','Silphidae','Silvanidae','Spercheidae','Sphaeritidae','Sphindidae','Staphylinidae','Tenebrionidae','Tetratomidae','Throscidae','Trogidae','Trogossitidae','Zopheridae','Adelidae','Alucitidae','Argyresthiidae','Autostichidae','Batrachedridae','Bedelliidae','Blastobasidae','Bombycidae','Brahmaeidae','Bucculatricidae','Castniidae','Chimabachidae','Choreutidae','Coleophoridae','Cosmopterigidae','Cossidae','Crambidae','Depressariidae','Douglasiidae','Drepanidae','Elachistidae','Endromidae','Epermeniidae','Erebidae','Eriocraniidae','Ethmiidae','Euteliidae','Gelechiidae','Geometridae','Glyphipterigidae','Gracillariidae','Heliozelidae','Hepialidae','Hesperiidae','Incurvariidae','Lasiocampidae','Limacodidae','Lycaenidae','Lyonetiidae','Lypusidae','Micropterigidae','Momphidae','Nepticulidae','Noctuidae','Nolidae','Notodontidae','Nymphalidae','Oecophoridae','Opostegidae','Papilionidae','Parametriotidae','Peleopodidae','Pieridae','Plutellidae','Praydidae','Prodoxidae','Psychidae','Pterophoridae','Pyralidae','Riodinidae','Roeslerstammiidae','Saturniidae','Schreckensteiniidae','Scythrididae','Sesiidae','Sphingidae','Stathmopodidae','Tineidae','Tischeriidae','Tortricidae','Urodidae','Yponomeutidae','Ypsolophidae','Zygaenidae')
 		OR p2.FullName IN ('Aderidae','Agyrtidae','Alexiidae','Anthicidae','Anthribidae','Apionidae','Attelabidae','Biphyllidae','Bolboceratidae','Bostrichidae','Bothrideridae','Buprestidae','Byrrhidae','Byturidae','Cantharidae','Carabidae','Cerambycidae','Cerylonidae','Chrysomelidae','Ciidae','Clambidae','Cleridae','Coccinellidae','Corylophidae','Cryptophagidae','Cucujidae','Curculionidae','Dascillidae','Dasytidae','Dermestidae','Derodontidae','Drilidae','Dryopidae','Dytiscidae','Elateridae','Elmidae','Endomychidae','Erotylidae','Eucinetidae','Eucnemidae','Georissidae','Geotrupidae','Gyrinidae','Haliplidae','Helophoridae','Heteroceridae','Histeridae','Hydraenidae','Hydrochidae','Hydrophilidae','Hygrobiidae','Kateretidae','Laemophloeidae','Lampyridae','Latridiidae','Leiodidae','Limnichidae','Lucanidae','Lycidae','Lymexylidae','Malachiidae','Megalopodidae','Melandryidae','Meloidae','Microsporidae','Monotomidae','Mordellidae','Mycetophagidae','Nanophyidae','Nemonychidae','Nitidulidae','Nosodendridae','Noteridae','Oedemeridae','Orsodacnidae','Phalacridae','Phloeostichidae','Phloiophilidae','Prostomidae','Psephenidae','Ptiliidae','Ptinidae','Pyrochroidae','Pythidae','Rhynchitidae','Ripiphoridae','Salpingidae','Scarabaeidae','Scirtidae','Scraptiidae','Silphidae','Silvanidae','Spercheidae','Sphaeritidae','Sphindidae','Staphylinidae','Tenebrionidae','Tetratomidae','Throscidae','Trogidae','Trogossitidae','Zopheridae','Adelidae','Alucitidae','Argyresthiidae','Autostichidae','Batrachedridae','Bedelliidae','Blastobasidae','Bombycidae','Brahmaeidae','Bucculatricidae','Castniidae','Chimabachidae','Choreutidae','Coleophoridae','Cosmopterigidae','Cossidae','Crambidae','Depressariidae','Douglasiidae','Drepanidae','Elachistidae','Endromidae','Epermeniidae','Erebidae','Eriocraniidae','Ethmiidae','Euteliidae','Gelechiidae','Geometridae','Glyphipterigidae','Gracillariidae','Heliozelidae','Hepialidae','Hesperiidae','Incurvariidae','Lasiocampidae','Limacodidae','Lycaenidae','Lyonetiidae','Lypusidae','Micropterigidae','Momphidae','Nepticulidae','Noctuidae','Nolidae','Notodontidae','Nymphalidae','Oecophoridae','Opostegidae','Papilionidae','Parametriotidae','Peleopodidae','Pieridae','Plutellidae','Praydidae','Prodoxidae','Psychidae','Pterophoridae','Pyralidae','Riodinidae','Roeslerstammiidae','Saturniidae','Schreckensteiniidae','Scythrididae','Sesiidae','Sphingidae','Stathmopodidae','Tineidae','Tischeriidae','Tortricidae','Urodidae','Yponomeutidae','Ypsolophidae','Zygaenidae')
 		OR  p3.FullName IN ('Aderidae','Agyrtidae','Alexiidae','Anthicidae','Anthribidae','Apionidae','Attelabidae','Biphyllidae','Bolboceratidae','Bostrichidae','Bothrideridae','Buprestidae','Byrrhidae','Byturidae','Cantharidae','Carabidae','Cerambycidae','Cerylonidae','Chrysomelidae','Ciidae','Clambidae','Cleridae','Coccinellidae','Corylophidae','Cryptophagidae','Cucujidae','Curculionidae','Dascillidae','Dasytidae','Dermestidae','Derodontidae','Drilidae','Dryopidae','Dytiscidae','Elateridae','Elmidae','Endomychidae','Erotylidae','Eucinetidae','Eucnemidae','Georissidae','Geotrupidae','Gyrinidae','Haliplidae','Helophoridae','Heteroceridae','Histeridae','Hydraenidae','Hydrochidae','Hydrophilidae','Hygrobiidae','Kateretidae','Laemophloeidae','Lampyridae','Latridiidae','Leiodidae','Limnichidae','Lucanidae','Lycidae','Lymexylidae','Malachiidae','Megalopodidae','Melandryidae','Meloidae','Microsporidae','Monotomidae','Mordellidae','Mycetophagidae','Nanophyidae','Nemonychidae','Nitidulidae','Nosodendridae','Noteridae','Oedemeridae','Orsodacnidae','Phalacridae','Phloeostichidae','Phloiophilidae','Prostomidae','Psephenidae','Ptiliidae','Ptinidae','Pyrochroidae','Pythidae','Rhynchitidae','Ripiphoridae','Salpingidae','Scarabaeidae','Scirtidae','Scraptiidae','Silphidae','Silvanidae','Spercheidae','Sphaeritidae','Sphindidae','Staphylinidae','Tenebrionidae','Tetratomidae','Throscidae','Trogidae','Trogossitidae','Zopheridae','Adelidae','Alucitidae','Argyresthiidae','Autostichidae','Batrachedridae','Bedelliidae','Blastobasidae','Bombycidae','Brahmaeidae','Bucculatricidae','Castniidae','Chimabachidae','Choreutidae','Coleophoridae','Cosmopterigidae','Cossidae','Crambidae','Depressariidae','Douglasiidae','Drepanidae','Elachistidae','Endromidae','Epermeniidae','Erebidae','Eriocraniidae','Ethmiidae','Euteliidae','Gelechiidae','Geometridae','Glyphipterigidae','Gracillariidae','Heliozelidae','Hepialidae','Hesperiidae','Incurvariidae','Lasiocampidae','Limacodidae','Lycaenidae','Lyonetiidae','Lypusidae','Micropterigidae','Momphidae','Nepticulidae','Noctuidae','Nolidae','Notodontidae','Nymphalidae','Oecophoridae','Opostegidae','Papilionidae','Parametriotidae','Peleopodidae','Pieridae','Plutellidae','Praydidae','Prodoxidae','Psychidae','Pterophoridae','Pyralidae','Riodinidae','Roeslerstammiidae','Saturniidae','Schreckensteiniidae','Scythrididae','Sesiidae','Sphingidae','Stathmopodidae','Tineidae','Tischeriidae','Tortricidae','Urodidae','Yponomeutidae','Ypsolophidae','Zygaenidae')
 		OR  p4.FullName IN ('Aderidae','Agyrtidae','Alexiidae','Anthicidae','Anthribidae','Apionidae','Attelabidae','Biphyllidae','Bolboceratidae','Bostrichidae','Bothrideridae','Buprestidae','Byrrhidae','Byturidae','Cantharidae','Carabidae','Cerambycidae','Cerylonidae','Chrysomelidae','Ciidae','Clambidae','Cleridae','Coccinellidae','Corylophidae','Cryptophagidae','Cucujidae','Curculionidae','Dascillidae','Dasytidae','Dermestidae','Derodontidae','Drilidae','Dryopidae','Dytiscidae','Elateridae','Elmidae','Endomychidae','Erotylidae','Eucinetidae','Eucnemidae','Georissidae','Geotrupidae','Gyrinidae','Haliplidae','Helophoridae','Heteroceridae','Histeridae','Hydraenidae','Hydrochidae','Hydrophilidae','Hygrobiidae','Kateretidae','Laemophloeidae','Lampyridae','Latridiidae','Leiodidae','Limnichidae','Lucanidae','Lycidae','Lymexylidae','Malachiidae','Megalopodidae','Melandryidae','Meloidae','Microsporidae','Monotomidae','Mordellidae','Mycetophagidae','Nanophyidae','Nemonychidae','Nitidulidae','Nosodendridae','Noteridae','Oedemeridae','Orsodacnidae','Phalacridae','Phloeostichidae','Phloiophilidae','Prostomidae','Psephenidae','Ptiliidae','Ptinidae','Pyrochroidae','Pythidae','Rhynchitidae','Ripiphoridae','Salpingidae','Scarabaeidae','Scirtidae','Scraptiidae','Silphidae','Silvanidae','Spercheidae','Sphaeritidae','Sphindidae','Staphylinidae','Tenebrionidae','Tetratomidae','Throscidae','Trogidae','Trogossitidae','Zopheridae','Adelidae','Alucitidae','Argyresthiidae','Autostichidae','Batrachedridae','Bedelliidae','Blastobasidae','Bombycidae','Brahmaeidae','Bucculatricidae','Castniidae','Chimabachidae','Choreutidae','Coleophoridae','Cosmopterigidae','Cossidae','Crambidae','Depressariidae','Douglasiidae','Drepanidae','Elachistidae','Endromidae','Epermeniidae','Erebidae','Eriocraniidae','Ethmiidae','Euteliidae','Gelechiidae','Geometridae','Glyphipterigidae','Gracillariidae','Heliozelidae','Hepialidae','Hesperiidae','Incurvariidae','Lasiocampidae','Limacodidae','Lycaenidae','Lyonetiidae','Lypusidae','Micropterigidae','Momphidae','Nepticulidae','Noctuidae','Nolidae','Notodontidae','Nymphalidae','Oecophoridae','Opostegidae','Papilionidae','Parametriotidae','Peleopodidae','Pieridae','Plutellidae','Praydidae','Prodoxidae','Psychidae','Pterophoridae','Pyralidae','Riodinidae','Roeslerstammiidae','Saturniidae','Schreckensteiniidae','Scythrididae','Sesiidae','Sphingidae','Stathmopodidae','Tineidae','Tischeriidae','Tortricidae','Urodidae','Yponomeutidae','Ypsolophidae','Zygaenidae')
 		    )
 */
 		AND t.Name NOT LIKE '%.%' AND t.Name NOT LIKE '%#%' AND t.Name NOT LIKE '%?%'  AND t.Name NOT LIKE '%:%' AND t.Name NOT LIKE '%*%' -- Leave out any trash taxa 
 		-- AND t.Author IS NOT NULL

	  ORDER BY t.RankID, p1.FullName, t.fullName
-- LIMIT 250000 -- OFFSET 250000 -- increase the offset by 250000 until all taxa are retrieved
-- add to beginning of output file::  INSERT INTO taxonname (spid,name,fullname,rankid,taxonRank, treedefid,parentfullname) VALUES